### PR TITLE
Add changes

### PR DESCRIPTION
**Pull request by Lucky-ESA**

### CODE REVIEW

**Comment by mcm1957** [comment]
OK, according to code review mowerActive seems to be still present but not used in a specific situation. So its ok to use minor version increase. I'll generate / release 2.2.0.

**Comment by mcm1957** [comment]
Version 2.2.0 released

A hint for README.md

"Fix incorrect number" will be translated to "Beheben sie die ungültige Nummer". The englishen wording is incorrect, it should read "Fixed incorrect number" or "Incorrect nmber has been fixed".

And don't worry, I learnt this through google translator after app 20 years of writing english revision histories before ...

**Comment by mcm1957** [comment]
@Lucky-ESA 
And feel free to create a request issue https://github.com/iobroker-community-adapters/info/issues to gain direct access.

**Comment by Lucky-ESA** [comment]
@mcm1957 
Thanks for your support.

**Pull request merged**
